language: csharp
solution: skalarprodukt.sln
before_install:
  - mkdir ./.paket
  - wget -O ./.paket/paket.bootstrapper.exe https://github.com/fsprojects/Paket/releases/download/4.0.7/paket.bootstrapper.exe
  - mono ./.paket/paket.bootstrapper.exe
install:
  - mono ./.paket/paket.exe add nuget FSharp.Compiler.Tools
  - mono ./.paket/paket.exe install
